### ISSUE TITLE
Mobile support files

### ISSUE THREAD

**Issue by wxnnvs** [JMcrafter26/pocket-client#1]
The first part
`PlatformInput.java`

the second part
`PlatformRuntime.java`

**Comment by wxnnvs** [comment]
idk what you need but it's in there

**Comment by JMcrafter26** [comment]
You didn't understand my, in order to modify and understand what resent client does, I need to be able to read the resent client code, which is obfuscated. I already tried various deobfuscaters but because of it size I am not able to deobfuscate it.

But thanks for your help

**Comment by wxnnvs** [comment]
[the resent source](https://github.com/ThisIsALegitUsername/Resent-1.8/tree/new)
no need to deobfuscate

**Comment by wxnnvs** [comment]
the code is somewhere [here](https://github.com/ThisIsALegitUsername/Resent-1.8/tree/new/src/teavm/java/net/lax1dude/eaglercraft/v1_8/internal)
im trying to get this working

**Comment by JMcrafter26** [comment]
Thank you! I was searching for the uncomplicated code on GitHub but couldn’t find it

**Comment by wxnnvs** [comment]
no problem! 
im trying to get it working as well but im getting this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
> Exception java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache [in thread "Daemon worker"]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by wxnnvs** [comment]
i got it
lemme upload to github

**Comment by JMcrafter26** [comment]
You mean to this repo?

**Comment by wxnnvs** [comment]
ye, i'll make a pr 
in like an hour or smt
gotta go now

**Comment by wxnnvs** [comment]
i've got to fix the offline download but [here](https://xinix.space/mobile) i have a working version (i hope)
